// This file is automatically generated by the auth integration. Do not edit it directly.
import { createFileRoute, Outlet, redirect, Link, useRouter } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import { Leaf, LayoutDashboard, Sprout, Camera, Wallet, User, LogOut, Radio, Shield, ShoppingBag } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { OfflineBadge } from "@/components/ui/offline-badge";
import { OfflineIndicator } from "@/components/ui/pwa-install-prompt";
import { useState, useRef, useCallback, useEffect } from "react";

export const Route = createFileRoute("/_authenticated")({
  ssr: false,
  beforeLoad: async () => {
    try {
      const { data, error } = await supabase.auth.getUser();
      // Retry une fois en cas d'erreur réseau
      if (error) {
        await new Promise((r) => setTimeout(r, 1000));
        const retry = await supabase.auth.getUser();
        if (retry.error || !retry.data.user) throw redirect({ to: "/auth" });
        return { user: retry.data.user };
      }
      if (!data.user) throw redirect({ to: "/auth" });
      return { user: data.user };
    } catch (e) {
      // Si c'est une redirect, on la propage
      if (e instanceof Error && e.message.includes("redirect")) throw e;
      // Si c'est une erreur réseau, on retente
      try {
        const retry = await supabase.auth.getUser();
        if (retry.error || !retry.data.user) throw redirect({ to: "/auth" });
        return { user: retry.data.user };
      } catch {
        throw redirect({ to: "/auth" });
      }
    }
  },
  component: AuthedLayout,
});

function AuthedLayout() {
  const router = useRouter();
  const queryClient = useQueryClient();
  
  // Swipe state
  const [dragOffset, setDragOffset] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const [targetPage, setTargetPage] = useState<"prev" | "next" | null>(null);
  
  const touchStartX = useRef<number>(0);
  const touchStartY = useRef<number>(0);
  const screenWidth = typeof window !== "undefined" ? window.innerWidth : 375;

  const routes = [
    { path: "/", label: "Accueil" },
    { path: "/parcels", label: "Parcelles" },
    { path: "/diagnose", label: "Diagnostic" },
    { path: "/sensors", label: "Capteurs" },
    { path: "/finance", label: "Finances" },
    { path: "/marketplace", label: "Marché" },
  ];

  const currentPath = router.state.location.pathname;
  const currentIndex = routes.findIndex(r => {
    const routePath = r.path === "/" ? "/dashboard" : r.path;
    return currentPath.startsWith(routePath) || currentPath === r.path;
  });

  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    // Seulement si on est près du bord gauche (comme WhatsApp)
    const touchX = e.touches[0].clientX;
    if (touchX > 50) return; // Ignore si pas près du bord
    
    // Ignorer si on touche un élément interactif (boutons, liens, inputs)
    const target = e.target as HTMLElement;
    if (target.closest('button, a, input, select, textarea, [role="button"]')) {
      return;
    }
    
    // Ignorer si on touche un élément avec scroll horizontal (carousel, galerie)
    if (target.closest('[data-swipe-ignore], .swiper-container, .carousel, [style*="overflow-x: auto"], [style*="overflow-x:auto"]')) {
      return;
    }
    
    // Vérifier si un parent a un scroll horizontal actif
    let current = target.parentElement;
    while (current && current !== document.body) {
      const style = window.getComputedStyle(current);
      if (style.overflowX === 'auto' || style.overflowX === 'scroll') {
        return; // C'est un conteneur scrollable horizontalement
      }
      current = current.parentElement;
    }
    
    touchStartX.current = touchX;
    touchStartY.current = e.touches[0].clientY;
    setIsDragging(true);
    setDragOffset(0);
    setTargetPage(null);
  }, []);

  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    if (!isDragging) return;
    
    const touchX = e.touches[0].clientX;
    const touchY = e.touches[0].clientY;
    const deltaX = touchX - touchStartX.current;
    const deltaY = touchY - touchStartY.current;
    
    // Ignore si mouvement principalement vertical
    if (Math.abs(deltaY) > Math.abs(deltaX)) return;
    
    // Résistance élastique sur les bords (comme iOS)
    const resistance = deltaX > 0 ? 0.5 : 0.8;
    setDragOffset(deltaX * resistance);
    
    // Déterminer la page cible
    if (deltaX > 30 && currentIndex > 0) {
      setTargetPage("prev");
    } else if (deltaX < -30 && currentIndex < routes.length - 1) {
      setTargetPage("next");
    } else {
      setTargetPage(null);
    }
  }, [isDragging, currentIndex, routes.length]);

  const handleTouchEnd = useCallback(() => {
    if (!isDragging) return;
    
    const threshold = screenWidth * 0.3; // 30% de l'écran pour valider
    
    if (targetPage === "prev" && Math.abs(dragOffset) > threshold) {
      const prevRoute = routes[currentIndex - 1];
      router.navigate({ to: prevRoute.path === "/" ? "/dashboard" : prevRoute.path });
    } else if (targetPage === "next" && Math.abs(dragOffset) > threshold) {
      const nextRoute = routes[currentIndex + 1];
      router.navigate({ to: nextRoute.path === "/" ? "/dashboard" : nextRoute.path });
    }
    
    // Reset
    setIsDragging(false);
    setDragOffset(0);
    setTargetPage(null);
  }, [isDragging, dragOffset, targetPage, currentIndex, routes, router, screenWidth]);

  // Empêcher le scroll horizontal pendant le drag
  useEffect(() => {
    if (isDragging) {
      document.body.style.overflowX = "hidden";
      return () => { document.body.style.overflowX = ""; };
    }
  }, [isDragging]);

  const isSuperAdmin = useQuery({
    queryKey: ["is-super-admin"],
    queryFn: async () => {
      const { data: u } = await supabase.auth.getUser();
      if (!u.user) return false;
      const { data } = await supabase
        .from("user_roles")
        .select("role")
        .eq("user_id", u.user.id)
        .eq("role", "super_admin")
        .maybeSingle();
      return !!data;
    },
    staleTime: 5 * 60 * 1000,
  }).data ?? false;

  async function signOut() {
    await queryClient.cancelQueries();
    queryClient.clear();
    await supabase.auth.signOut();
    router.navigate({ to: "/auth", replace: true });
  }

  // Calcul de la transformation pour l'animation fluide
  const mainContentStyle: React.CSSProperties = {
    transform: isDragging ? `translateX(${dragOffset}px)` : undefined,
    transition: isDragging ? "none" : "transform 0.3s cubic-bezier(0.25, 0.46, 0.45, 0.94)",
    willChange: "transform",
  };

  return (
    <div 
      className="flex min-h-screen flex-col bg-background pb-20 overflow-hidden"
    >
      <header className="sticky top-0 z-30 border-b border-border/60 bg-background/90 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3">
          <Link to="/dashboard" className="flex items-center gap-2 font-bold text-primary">
            <Leaf className="h-5 w-5" />
            <span>AgroSphere</span>
          </Link>
          <div className="flex items-center gap-2">
            <Link
              to="/profile"
              className="inline-flex items-center gap-1 rounded-full border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-muted data-[status=active]:border-primary data-[status=active]:text-primary"
              activeProps={{ "data-status": "active" }}
            >
              <User className="h-3.5 w-3.5" />
              Profil
            </Link>
            <button
              onClick={signOut}
              className="inline-flex items-center gap-1 rounded-full border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-muted"
            >
              <LogOut className="h-3.5 w-3.5" />
              Quitter
            </button>
          </div>
        </div>
      </header>

      <main 
        className="mx-auto w-full max-w-3xl flex-1 px-4 py-5"
        style={mainContentStyle}
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        <Outlet />
      </main>

      {/* Bottom nav avec Dashboard en premier onglet */}
      <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-border bg-background/95 backdrop-blur">
        <div className={`mx-auto grid ${isSuperAdmin ? "grid-cols-7" : "grid-cols-6"}`}>
          <NavItem to="/" icon={<LayoutDashboard className="h-5 w-5" />} label="Accueil" />
          <NavItem to="/parcels" icon={<Sprout className="h-5 w-5" />} label="Parcelles" />
          <NavItem to="/diagnose" icon={<Camera className="h-5 w-5" />} label="Diagnostic" />
          <NavItem to="/sensors" icon={<Radio className="h-5 w-5" />} label="Capteurs" />
          <NavItem to="/finance" icon={<Wallet className="h-5 w-5" />} label="Finances" />
          <NavItem to="/marketplace" icon={<ShoppingBag className="h-5 w-5" />} label="Marché" />
          {isSuperAdmin && (
            <NavItem to="/admin" icon={<Shield className="h-5 w-5" />} label="Admin" />
          )}
        </div>
      </nav>

      {/* Badge offline - Zones rurales */}
      <OfflineBadge />

      {/* Indicateur offline */}
      <OfflineIndicator />
    </div>
  );
}

function NavItem({ to, icon, label }: { to: string; icon: React.ReactNode; label: string }) {
  return (
    <Link
      to={to}
      className="flex flex-col items-center justify-center gap-1 py-3 min-h-[48px] text-xs font-medium text-muted-foreground data-[status=active]:text-primary"
      activeProps={{ "data-status": "active" }}
    >
      {icon}
      <span className="text-center">{label}</span>
    </Link>
  );
}