// This file is automatically generated by the auth integration. Do not edit it directly.
import { createFileRoute, Outlet, redirect, Link, useRouter } from "@tanstack/react-router";
import { supabase } from "@/integrations/supabase/client";
import { Leaf, LayoutDashboard, Sprout, Camera, Wallet, User, LogOut, Radio, Shield, ShoppingBag } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { OfflineBadge } from "@/components/ui/offline-badge";
import { OfflineIndicator } from "@/components/ui/pwa-install-prompt";
import { useState, useRef, useCallback } from "react";

export const Route = createFileRoute("/_authenticated")({
  ssr: false,
  beforeLoad: async () => {
    try {
      const { data, error } = await supabase.auth.getUser();
      // Retry une fois en cas d'erreur réseau
      if (error) {
        await new Promise((r) => setTimeout(r, 1000));
        const retry = await supabase.auth.getUser();
        if (retry.error || !retry.data.user) throw redirect({ to: "/auth" });
        return { user: retry.data.user };
      }
      if (!data.user) throw redirect({ to: "/auth" });
      return { user: data.user };
    } catch (e) {
      // Si c'est une redirect, on la propage
      if (e instanceof Error && e.message.includes("redirect")) throw e;
      // Si c'est une erreur réseau, on retente
      try {
        const retry = await supabase.auth.getUser();
        if (retry.error || !retry.data.user) throw redirect({ to: "/auth" });
        return { user: retry.data.user };
      } catch {
        throw redirect({ to: "/auth" });
      }
    }
  },
  component: AuthedLayout,
});

function AuthedLayout() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const [isSwiping, setIsSwiping] = useState(false);
  const touchStartX = useRef<number>(0);
  const touchEndX = useRef<number>(0);

  const routes = [
    { path: "/", label: "Accueil" },
    { path: "/parcels", label: "Parcelles" },
    { path: "/diagnose", label: "Diagnostic" },
    { path: "/sensors", label: "Capteurs" },
    { path: "/finance", label: "Finances" },
    { path: "/marketplace", label: "Marché" },
  ];

  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    touchStartX.current = e.touches[0].clientX;
    setIsSwiping(true);
  }, []);

  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    if (!isSwiping) return;
    touchEndX.current = e.touches[0].clientX;
  }, [isSwiping]);

  const handleTouchEnd = useCallback(() => {
    if (!isSwiping) return;
    
    const swipeDistance = touchEndX.current - touchStartX.current;
    const threshold = 50; // Minimum swipe distance in px
    
    if (Math.abs(swipeDistance) < threshold) {
      setIsSwiping(false);
      return;
    }

    const currentPath = router.state.location.pathname;
    const currentIndex = routes.findIndex(r => {
      const routePath = r.path === "/" ? "/dashboard" : r.path;
      return currentPath.startsWith(routePath);
    });

    if (currentIndex === -1) {
      setIsSwiping(false);
      return;
    }

    // Swipe left (next page)
    if (swipeDistance < -threshold && currentIndex < routes.length - 1) {
      const nextRoute = routes[currentIndex + 1];
      router.navigate({ to: nextRoute.path === "/" ? "/dashboard" : nextRoute.path });
    }
    
    // Swipe right (previous page)
    if (swipeDistance > threshold && currentIndex > 0) {
      const prevRoute = routes[currentIndex - 1];
      router.navigate({ to: prevRoute.path === "/" ? "/dashboard" : prevRoute.path });
    }

    setIsSwiping(false);
  }, [isSwiping, router, routes]);

  const isSuperAdmin = useQuery({
    queryKey: ["is-super-admin"],
    queryFn: async () => {
      const { data: u } = await supabase.auth.getUser();
      if (!u.user) return false;
      const { data } = await supabase
        .from("user_roles")
        .select("role")
        .eq("user_id", u.user.id)
        .eq("role", "super_admin")
        .maybeSingle();
      return !!data;
    },
    staleTime: 5 * 60 * 1000,
  }).data ?? false;

  async function signOut() {
    await queryClient.cancelQueries();
    queryClient.clear();
    await supabase.auth.signOut();
    router.navigate({ to: "/auth", replace: true });
  }

  const cols = isSuperAdmin ? "grid-cols-7" : "grid-cols-6";

  return (
    <div 
      className="flex min-h-screen flex-col bg-background pb-20"
      onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove}
      onTouchEnd={handleTouchEnd}
    >
      <header className="sticky top-0 z-30 border-b border-border/60 bg-background/90 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-3">
          <Link to="/dashboard" className="flex items-center gap-2 font-bold text-primary">
            <Leaf className="h-5 w-5" />
            <span>AgroSphere</span>
          </Link>
          <div className="flex items-center gap-2">
            <Link
              to="/profile"
              className="inline-flex items-center gap-1 rounded-full border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-muted data-[status=active]:border-primary data-[status=active]:text-primary"
              activeProps={{ "data-status": "active" }}
            >
              <User className="h-3.5 w-3.5" />
              Profil
            </Link>
            <button
              onClick={signOut}
              className="inline-flex items-center gap-1 rounded-full border border-border px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-muted"
            >
              <LogOut className="h-3.5 w-3.5" />
              Quitter
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-5">
        <Outlet />
      </main>

      {/* Bottom nav avec Dashboard en premier onglet */}
      <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-border bg-background/95 backdrop-blur">
        <div className={`mx-auto grid max-w-3xl ${cols}`}>
          <NavItem to="/" icon={<LayoutDashboard className="h-5 w-5" />} label="Accueil" />
          <NavItem to="/parcels" icon={<Sprout className="h-5 w-5" />} label="Parcelles" />
          <NavItem to="/diagnose" icon={<Camera className="h-5 w-5" />} label="Diagnostic" />
          <NavItem to="/sensors" icon={<Radio className="h-5 w-5" />} label="Capteurs" />
          <NavItem to="/finance" icon={<Wallet className="h-5 w-5" />} label="Finances" />
          <NavItem to="/marketplace" icon={<ShoppingBag className="h-5 w-5" />} label="Marché" />
          {isSuperAdmin && (
            <NavItem to="/admin" icon={<Shield className="h-5 w-5" />} label="Admin" />
          )}
        </div>
      </nav>

      {/* Badge offline - Zones rurales */}
      <OfflineBadge />

      {/* Indicateur offline */}
      <OfflineIndicator />
    </div>
  );
}

function NavItem({ to, icon, label }: { to: string; icon: React.ReactNode; label: string }) {
  return (
    <Link
      to={to}
      className="flex flex-col items-center justify-center gap-1 py-3 min-h-[48px] text-xs font-medium text-muted-foreground data-[status=active]:text-primary"
      activeProps={{ "data-status": "active" }}
    >
      {icon}
      <span className="text-center">{label}</span>
    </Link>
  );
}