/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CreateOfferRouteImport } from './routes/create-offer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceCreateRouteImport } from './routes/marketplace.create'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedSensorsRouteImport } from './routes/_authenticated/sensors'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedParcelsRouteImport } from './routes/_authenticated/parcels'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDiagnoseRouteImport } from './routes/_authenticated/diagnose'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCropEventsRouteImport } from './routes/_authenticated/crop-events'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMarketplaceOrdersRouteImport } from './routes/_authenticated/marketplace.orders'
import { Route as AuthenticatedMarketplaceMyOffersRouteImport } from './routes/_authenticated/marketplace.my-offers'
import { Route as AuthenticatedMarketplaceMessagesRouteImport } from './routes/_authenticated/marketplace.messages'
import { Route as AuthenticatedFinancesCreditRouteImport } from './routes/_authenticated/finances.credit'
import { Route as AuthenticatedFinancesAddRouteImport } from './routes/_authenticated/finances.add'
import { Route as ApiPublicSensorsIngestRouteImport } from './routes/api/public/sensors/ingest'
import { Route as ApiPublicSensorsCommandsRouteImport } from './routes/api/public/sensors/commands'
import { Route as AuthenticatedMarketplaceIdEditRouteImport } from './routes/_authenticated/marketplace.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOfferRoute = CreateOfferRouteImport.update({
  id: '/create-offer',
  path: '/create-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCreateRoute = MarketplaceCreateRouteImport.update({
  id: '/marketplace/create',
  path: '/marketplace/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedSensorsRoute = AuthenticatedSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParcelsRoute = AuthenticatedParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnoseRoute = AuthenticatedDiagnoseRouteImport.update({
  id: '/diagnose',
  path: '/diagnose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCropEventsRoute = AuthenticatedCropEventsRouteImport.update({
  id: '/crop-events',
  path: '/crop-events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceOrdersRoute =
  AuthenticatedMarketplaceOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceMyOffersRoute =
  AuthenticatedMarketplaceMyOffersRouteImport.update({
    id: '/my-offers',
    path: '/my-offers',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedMarketplaceMessagesRoute =
  AuthenticatedMarketplaceMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)
const AuthenticatedFinancesCreditRoute =
  AuthenticatedFinancesCreditRouteImport.update({
    id: '/finances/credit',
    path: '/finances/credit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancesAddRoute =
  AuthenticatedFinancesAddRouteImport.update({
    id: '/finances/add',
    path: '/finances/add',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSensorsIngestRoute = ApiPublicSensorsIngestRouteImport.update({
  id: '/api/public/sensors/ingest',
  path: '/api/public/sensors/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSensorsCommandsRoute =
  ApiPublicSensorsCommandsRouteImport.update({
    id: '/api/public/sensors/commands',
    path: '/api/public/sensors/commands',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMarketplaceIdEditRoute =
  AuthenticatedMarketplaceIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AuthenticatedMarketplaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/create-offer': typeof CreateOfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/crop-events': typeof AuthenticatedCropEventsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parcels': typeof AuthenticatedParcelsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/create': typeof MarketplaceCreateRoute
  '/finances/add': typeof AuthenticatedFinancesAddRoute
  '/finances/credit': typeof AuthenticatedFinancesCreditRoute
  '/marketplace/messages': typeof AuthenticatedMarketplaceMessagesRoute
  '/marketplace/my-offers': typeof AuthenticatedMarketplaceMyOffersRoute
  '/marketplace/orders': typeof AuthenticatedMarketplaceOrdersRoute
  '/marketplace/$id/edit': typeof AuthenticatedMarketplaceIdEditRoute
  '/api/public/sensors/commands': typeof ApiPublicSensorsCommandsRoute
  '/api/public/sensors/ingest': typeof ApiPublicSensorsIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/create-offer': typeof CreateOfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/crop-events': typeof AuthenticatedCropEventsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnose': typeof AuthenticatedDiagnoseRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parcels': typeof AuthenticatedParcelsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/create': typeof MarketplaceCreateRoute
  '/finances/add': typeof AuthenticatedFinancesAddRoute
  '/finances/credit': typeof AuthenticatedFinancesCreditRoute
  '/marketplace/messages': typeof AuthenticatedMarketplaceMessagesRoute
  '/marketplace/my-offers': typeof AuthenticatedMarketplaceMyOffersRoute
  '/marketplace/orders': typeof AuthenticatedMarketplaceOrdersRoute
  '/marketplace/$id/edit': typeof AuthenticatedMarketplaceIdEditRoute
  '/api/public/sensors/commands': typeof ApiPublicSensorsCommandsRoute
  '/api/public/sensors/ingest': typeof ApiPublicSensorsIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/create-offer': typeof CreateOfferRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/crop-events': typeof AuthenticatedCropEventsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnose': typeof AuthenticatedDiagnoseRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/parcels': typeof AuthenticatedParcelsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/sensors': typeof AuthenticatedSensorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/marketplace/create': typeof MarketplaceCreateRoute
  '/_authenticated/finances/add': typeof AuthenticatedFinancesAddRoute
  '/_authenticated/finances/credit': typeof AuthenticatedFinancesCreditRoute
  '/_authenticated/marketplace/messages': typeof AuthenticatedMarketplaceMessagesRoute
  '/_authenticated/marketplace/my-offers': typeof AuthenticatedMarketplaceMyOffersRoute
  '/_authenticated/marketplace/orders': typeof AuthenticatedMarketplaceOrdersRoute
  '/_authenticated/marketplace/$id/edit': typeof AuthenticatedMarketplaceIdEditRoute
  '/api/public/sensors/commands': typeof ApiPublicSensorsCommandsRoute
  '/api/public/sensors/ingest': typeof ApiPublicSensorsIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create-offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/crop-events'
    | '/dashboard'
    | '/diagnose'
    | '/finance'
    | '/marketplace'
    | '/onboarding'
    | '/parcels'
    | '/profile'
    | '/sensors'
    | '/auth/callback'
    | '/marketplace/$id'
    | '/marketplace/create'
    | '/finances/add'
    | '/finances/credit'
    | '/marketplace/messages'
    | '/marketplace/my-offers'
    | '/marketplace/orders'
    | '/marketplace/$id/edit'
    | '/api/public/sensors/commands'
    | '/api/public/sensors/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/crop-events'
    | '/dashboard'
    | '/diagnose'
    | '/finance'
    | '/marketplace'
    | '/onboarding'
    | '/parcels'
    | '/profile'
    | '/sensors'
    | '/auth/callback'
    | '/marketplace/$id'
    | '/marketplace/create'
    | '/finances/add'
    | '/finances/credit'
    | '/marketplace/messages'
    | '/marketplace/my-offers'
    | '/marketplace/orders'
    | '/marketplace/$id/edit'
    | '/api/public/sensors/commands'
    | '/api/public/sensors/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/create-offer'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/crop-events'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnose'
    | '/_authenticated/finance'
    | '/_authenticated/marketplace'
    | '/_authenticated/onboarding'
    | '/_authenticated/parcels'
    | '/_authenticated/profile'
    | '/_authenticated/sensors'
    | '/auth/callback'
    | '/marketplace/$id'
    | '/marketplace/create'
    | '/_authenticated/finances/add'
    | '/_authenticated/finances/credit'
    | '/_authenticated/marketplace/messages'
    | '/_authenticated/marketplace/my-offers'
    | '/_authenticated/marketplace/orders'
    | '/_authenticated/marketplace/$id/edit'
    | '/api/public/sensors/commands'
    | '/api/public/sensors/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CreateOfferRoute: typeof CreateOfferRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  MarketplaceCreateRoute: typeof MarketplaceCreateRoute
  ApiPublicSensorsCommandsRoute: typeof ApiPublicSensorsCommandsRoute
  ApiPublicSensorsIngestRoute: typeof ApiPublicSensorsIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-offer': {
      id: '/create-offer'
      path: '/create-offer'
      fullPath: '/create-offer'
      preLoaderRoute: typeof CreateOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/create': {
      id: '/marketplace/create'
      path: '/marketplace/create'
      fullPath: '/marketplace/create'
      preLoaderRoute: typeof MarketplaceCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/sensors': {
      id: '/_authenticated/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AuthenticatedSensorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parcels': {
      id: '/_authenticated/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof AuthenticatedParcelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnose': {
      id: '/_authenticated/diagnose'
      path: '/diagnose'
      fullPath: '/diagnose'
      preLoaderRoute: typeof AuthenticatedDiagnoseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crop-events': {
      id: '/_authenticated/crop-events'
      path: '/crop-events'
      fullPath: '/crop-events'
      preLoaderRoute: typeof AuthenticatedCropEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/orders': {
      id: '/_authenticated/marketplace/orders'
      path: '/orders'
      fullPath: '/marketplace/orders'
      preLoaderRoute: typeof AuthenticatedMarketplaceOrdersRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/my-offers': {
      id: '/_authenticated/marketplace/my-offers'
      path: '/my-offers'
      fullPath: '/marketplace/my-offers'
      preLoaderRoute: typeof AuthenticatedMarketplaceMyOffersRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/marketplace/messages': {
      id: '/_authenticated/marketplace/messages'
      path: '/messages'
      fullPath: '/marketplace/messages'
      preLoaderRoute: typeof AuthenticatedMarketplaceMessagesRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
    '/_authenticated/finances/credit': {
      id: '/_authenticated/finances/credit'
      path: '/finances/credit'
      fullPath: '/finances/credit'
      preLoaderRoute: typeof AuthenticatedFinancesCreditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances/add': {
      id: '/_authenticated/finances/add'
      path: '/finances/add'
      fullPath: '/finances/add'
      preLoaderRoute: typeof AuthenticatedFinancesAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sensors/ingest': {
      id: '/api/public/sensors/ingest'
      path: '/api/public/sensors/ingest'
      fullPath: '/api/public/sensors/ingest'
      preLoaderRoute: typeof ApiPublicSensorsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sensors/commands': {
      id: '/api/public/sensors/commands'
      path: '/api/public/sensors/commands'
      fullPath: '/api/public/sensors/commands'
      preLoaderRoute: typeof ApiPublicSensorsCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/marketplace/$id/edit': {
      id: '/_authenticated/marketplace/$id/edit'
      path: '/$id/edit'
      fullPath: '/marketplace/$id/edit'
      preLoaderRoute: typeof AuthenticatedMarketplaceIdEditRouteImport
      parentRoute: typeof AuthenticatedMarketplaceRoute
    }
  }
}

interface AuthenticatedMarketplaceRouteChildren {
  AuthenticatedMarketplaceMessagesRoute: typeof AuthenticatedMarketplaceMessagesRoute
  AuthenticatedMarketplaceMyOffersRoute: typeof AuthenticatedMarketplaceMyOffersRoute
  AuthenticatedMarketplaceOrdersRoute: typeof AuthenticatedMarketplaceOrdersRoute
  AuthenticatedMarketplaceIdEditRoute: typeof AuthenticatedMarketplaceIdEditRoute
}

const AuthenticatedMarketplaceRouteChildren: AuthenticatedMarketplaceRouteChildren =
  {
    AuthenticatedMarketplaceMessagesRoute:
      AuthenticatedMarketplaceMessagesRoute,
    AuthenticatedMarketplaceMyOffersRoute:
      AuthenticatedMarketplaceMyOffersRoute,
    AuthenticatedMarketplaceOrdersRoute: AuthenticatedMarketplaceOrdersRoute,
    AuthenticatedMarketplaceIdEditRoute: AuthenticatedMarketplaceIdEditRoute,
  }

const AuthenticatedMarketplaceRouteWithChildren =
  AuthenticatedMarketplaceRoute._addFileChildren(
    AuthenticatedMarketplaceRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCropEventsRoute: typeof AuthenticatedCropEventsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnoseRoute: typeof AuthenticatedDiagnoseRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedParcelsRoute: typeof AuthenticatedParcelsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSensorsRoute: typeof AuthenticatedSensorsRoute
  AuthenticatedFinancesAddRoute: typeof AuthenticatedFinancesAddRoute
  AuthenticatedFinancesCreditRoute: typeof AuthenticatedFinancesCreditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCropEventsRoute: AuthenticatedCropEventsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnoseRoute: AuthenticatedDiagnoseRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedParcelsRoute: AuthenticatedParcelsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSensorsRoute: AuthenticatedSensorsRoute,
  AuthenticatedFinancesAddRoute: AuthenticatedFinancesAddRoute,
  AuthenticatedFinancesCreditRoute: AuthenticatedFinancesCreditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CreateOfferRoute: CreateOfferRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceCreateRoute: MarketplaceCreateRoute,
  ApiPublicSensorsCommandsRoute: ApiPublicSensorsCommandsRoute,
  ApiPublicSensorsIngestRoute: ApiPublicSensorsIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
